version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: |
            npm run build # If necessary, build your extension
            npm test -- src/script.test.js # Specify the test file or pattern for your script.js tests
