version: 2.1

executors:
  node-19.6.0:
    docker:
      - image: circleci/node:19.6.0

jobs:
  build:
    executor: node-19.6.0
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run:
          name: Print Dependencies
          command: npm ls
      - run: npm run test
