version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
       # Print dependencies
      - run:
          name: Print Dependencies
          command: npm ls
      - run:
          name: Run tests
          command: npm test
          environment:
            API_KEY: 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


      