version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:19.6
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
       # Print dependencies
      - run:
          name: Print Dependencies
          command: npm ls
      - run: npm run test


      